sudo: false

os: linux

language: python

branches:
  only:
    - master

git:
  submodules: false

install:
  - pipenv install --dev

script:
  - mkdir -p build
  - cd build
  - cmake .. -DBUILD_TESTING=ON $CMAKE_ARGS && make
  - mkdir -p ../docs/_build/html && touch ../docs/_build/html/.nojekyll
  - ctest --output-on-failure

jobs:
  include:
    # Xenial default: gcc 5, python 3.5
    # Bionic default: gcc 7, python 3.6
    # Focal default:  gcc 9, python 3.8

    # 1. Bionic gcc 7, python 3.6 (default)
    - dist: bionic
      python:
        - "3.6"
      env:
        - CMAKE_ARGS="-DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.6 -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython3.6m.so -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python3.6m"

    # 2. Bionic gcc 7, python 3.7
    - dist: bionic
      python:
        - "3.7"

    # 3. Bionic gcc 8, python 3.6
    - dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      python:
        - "3.6"
      env:
        - CMAKE_ARGS="-DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.6 -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython3.6m.so -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python3.6m"

    # 4. Focal gcc 9, python 3.8 (default)
    - dist: focal
      python:
        - "3.8"
      env:
        - CMAKE_ARGS="-DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.8 -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython3.8m.so -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python3.8m"

    # 5. Focal gcc 9, python 3.9
    - dist: focal
      python:
        - "3.9"
      env:
        - CMAKE_ARGS="-DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.9 -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython3.9m.so -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python3.9m"

    # 6. Focal gcc 10, python 3.8
    - dist: focal
      python:
        - "3.8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"
        - CMAKE_ARGS="-DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.8 -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython3.8m.so -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python3.8m"

    # 7. Docs
    - dist: focal
      python:
        - "3.7"
      addons:
        apt:
          - doxygen
      env:
        - CMAKE_ARGS="-DBUILD_DOCS=ON"
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/_build/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: master
